workflows:
  react-android-workflow:
    name: React Android Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      vars:
        PACKAGE_NAME: "com.tibzee.app"
      node: v18.17.0
      java: '11'
    scripts:
      - name: Install npm dependencies
        script: |
          npm ci
      - name: Build web app
        script: |
          npm run build
      - name: Add Android platform (if not exists)
        script: |
          npx cap add android || echo "Android platform already exists"
      - name: Sync web assets to native project
        script: |
          npx cap sync android
      - name: Set up local.properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Build Android APK (Debug)
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
      - android/app/build/outputs/**/mapping.txt
    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: true

  react-web-workflow:
    name: React Web Build
    max_build_duration: 60
    instance_type: linux_x2
    environment:
      node: v18.17.0
    scripts:
      - name: Install npm dependencies
        script: |
          npm ci
      - name: Lint code
        script: |
          npm run lint
      - name: Build web app
        script: |
          npm run build
      - name: Test build
        script: |
          npm run preview &
          sleep 5
          curl -f http://localhost:4173 || exit 1
    artifacts:
      - dist/
    publishing:
      email:
        recipients:
          - kushashanth@gmail.com
        notify:
          success: true
          failure: true
